import type { Recipe } from "../domain/models";

export const mockRecipes: Recipe[] = [
	{
		id: "1",
		image: "https://img.spoonacular.com/recipes/641014-556x370.jpg",
		title: "Cucumber Mint Tea Sandwiches",
		readyInMinutes: 45,
		servings: 8,
		sourceUrl: "https://www.foodista.com/recipe/33CV8WS5/cucumber-mint-tea-sandwiches",
		extendedIngredients: [
			{
				id: 18064,
				image: "white-bread.jpg",
				name: "bread",
				amount: 4,
				unit: "slices",
			},
			{
				id: 11206,
				image: "cucumber.jpg",
				name: "cucumber",
				amount: 0.5,
				unit: "",
			},
			{
				id: 19911,
				image: "maple-syrup.png",
				name: "wasabi maple spread",
				amount: 3,
				unit: "tablespoons",
			},
			{
				id: 1002030,
				image: "pepper.jpg",
				name: "pepper grinder",
				amount: 8,
				unit: "servings",
			},
			{
				id: 2064,
				image: "mint.jpg",
				name: "mint leaves",
				amount: 8,
				unit: "servings",
			},
			{
				id: 2045,
				image: "dill.jpg",
				name: "dill",
				amount: 8,
				unit: "servings",
			},
			{
				id: 98975,
				image: "mayonnaise.png",
				name: "vegenaise",
				amount: 2,
				unit: "tablespoons",
			},
			{
				id: 19911,
				image: "maple-syrup.png",
				name: "maple syrup",
				amount: 1,
				unit: "tablespoon",
			},
			{
				id: 10111990,
				image: "wasabi-powder.png",
				name: "wasabi powder",
				amount: 2,
				unit: "teaspoons",
			},
			{
				id: 1002030,
				image: "pepper.jpg",
				name: "pepper",
				amount: 1,
				unit: "dash",
			},
		],
		summary:
			'Cucumber Mint Tea Sandwiches is a <b>dairy free, lacto ovo vegetarian, and vegan</b> recipe with 8 servings. One portion of this dish contains around <b>2g of protein</b>, <b>3g of fat</b>, and a total of <b>91 calories</b>. For <b>49 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista requires wasabi powder, cucumber, wasabi maple spread, and maple syrup. A few people really liked this hor d\'oeuvre. 20 people have tried and liked this recipe. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 24%</b>. This score is rather bad. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/cucumber-mint-tea-sandwiches-1408981">Cucumber Mint Tea Sandwiches</a>, <a href="https://spoonacular.com/recipes/cucumber-mint-tea-sandwiches-103264">Cucumber Mint Tea Sandwiches</a>, and <a href="https://spoonacular.com/recipes/cucumber-mint-chutney-tea-sandwiches-23083">Cucumber-Mint Chutney Tea Sandwiches</a>.',

		instructions:
			"Directions:\nWhip together the spread, thinly slice the cucumbers. You can do thick crunchy slices, or thin silky slices - your choice. Gather your fresh herbs, rinse and pat dry.\nSpread a very thin layer of spread on all inside surfaces of bread.\nLayer cucumber on top of the spread. Next, add a layer of mint, dill. You can add both herbs to each sandwich or do half dill and half mint. Grind fresh black pepper inside sandwiches before slicing.\nClose sandwich and slice into quarter cubes or triangles.\nPlate and serve.\nOptional: add a thin layer of spicy sun dried tomato spread or a dash of red pepper flakes for an extra spicy kick of flavor. Another pretty addition would be edible flowers - add inside the sandwiches or as an edible garnish to the serving patter.",
	},
	{
		id: "2",
		image: "https://img.spoonacular.com/recipes/638940-556x370.jpg",
		title: "Chocolate Chip Peanut Butter Banana Cookies",
		readyInMinutes: 45,
		servings: 24,
		sourceUrl: "https://www.foodista.com/recipe/RZGVSKMQ/chocolate-chip-peanut-butter-banana-cookies",
		extendedIngredients: [
			{
				id: 18369,
				image: "white-powder.jpg",
				name: "baking powder",
				amount: 0.5,
				unit: "teaspoon",
			},
			{
				id: 18372,
				image: "white-powder.jpg",
				name: "baking soda",
				amount: 0.5,
				unit: "teaspoon",
			},
			{
				id: 9040,
				image: "bananas.jpg",
				name: "bananas",
				amount: 2,
				unit: "",
			},
			{
				id: 19334,
				image: "light-brown-sugar.jpg",
				name: "brown sugar",
				amount: 0.5,
				unit: "cup",
			},
			{
				id: 1001,
				image: "butter-sliced.jpg",
				name: "butter",
				amount: 1,
				unit: "Tbs",
			},
			{
				id: 10019146,
				image: "chocolate-chips.jpg",
				name: "chocolate chips",
				amount: 1,
				unit: "cup",
			},
			{
				id: 2010,
				image: "cinnamon.jpg",
				name: "cinnamon",
				amount: 0.5,
				unit: "teaspoon",
			},
			{
				id: 10116098,
				image: "peanut-butter.png",
				name: "creamy peanut butter",
				amount: 0.5,
				unit: "cup",
			},
			{
				id: 1123,
				image: "egg.png",
				name: "egg",
				amount: 1,
				unit: "",
			},
			{
				id: 20081,
				image: "flour.png",
				name: "flour",
				amount: 1.25,
				unit: "cup",
			},
			{
				id: 10719335,
				image: "sugar-in-bowl.png",
				name: "granulated sugar",
				amount: 1.25,
				unit: "cup",
			},
			{
				id: 2047,
				image: "salt.jpg",
				name: "salt",
				amount: 0.5,
				unit: "teaspoon",
			},
			{
				id: 1052050,
				image: "vanilla.jpg",
				name: "vanilla",
				amount: 1,
				unit: "teaspoon",
			},
		],
		summary:
			'Forget going out to eat or ordering takeout every time you crave Southern food. Try making Chocolate Chip Peanut Butter Banana Cookies at home. One serving contains <b>167 calories</b>, <b>3g of protein</b>, and <b>5g of fat</b>. For <b>16 cents per serving</b>, you get a dessert that serves 24. 81 person were impressed by this recipe. Head to the store and pick up egg, granulated sugar, bananas, and a few other things to make it today. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 17%</b>, this dish is not so awesome. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/banana-peanut-butter-chocolate-chip-cookies-531368">Banana, Peanut Butter, Chocolate Chip Cookies</a>, <a href="https://spoonacular.com/recipes/chocolate-chip-peanut-butter-banana-cookies-684339">Chocolate Chip Peanut Butter Banana Cookies</a>, and <a href="https://spoonacular.com/recipes/peanut-butter-chocolate-and-banana-chip-cookies-655260">Peanut Butter Chocolate and Banana Chip Cookies</a>.',
		instructions:
			"<ol><li>Preheat oven to 350 degrees.</li><li>In a large bowl, mash 2 ripened bananas.</li><li>Add butter, peanut butter, both sugars, egg, vanilla and stir.</li><li>In a separate bowl, whisk together flour, baking powder, baking soda, cinnamon and salt.</li><li>Add dry ingredients to banana mixture and stir until combined (do not stir this to death!)</li><li>Add mini chocolate chips and briefly stir.</li><li>Drop by large spoonful onto parchment lined baking sheet.</li><li>In a small bowl, pour 1/4 cup of sugar and 1/2 tsp of cinnamon and stir.  Sprinkle over unbaked cookies.</li><li>Bake for 10-12 minutes or until slightly golden brown.  My oven is hot, and only needs 10 minutes.  </li></ol>",
	},
];

export const mockRecipe: Recipe = mockRecipes[0];
